/*global pair: false*/

var LESSONS = [];

LESSONS[0] = [  pair({ word: 'конфета', translation: 'あめ'}), pair({ word: 'стул', translation: 'いす'}),
				pair({ word: 'море', translation: 'うみ'}), pair({ word: 'станция', translation: 'えき'}),
				pair({ word: 'зеленый чай', translation: 'おちゃ'}), pair({ word: 'лицо', translation: 'かお'}),
				pair({ word: 'дерево', translation: 'き'}), pair({ word: 'небо', translation: 'そら'}),
				pair({ word: 'дом', translation: 'いえ'}), pair({ word: 'книга', translation: 'ほん'}),
				pair({ word: 'стол', translation: 'つくえ'}), pair({ word: 'раковина', translation: 'かい'}),
				pair({ word: 'одежда', translation: 'ふく'}), pair({ word: 'деньги', translation: 'おかね'}),
				pair({ word: 'учитель', translation: 'せんせい'}), pair({ word: 'человек', translation: 'ひと'}),
				pair({ word: 'имя', translation: 'なまえ'}), pair({ word: 'мужчина', translation: 'おとこ'}),
				pair({ word: 'женщина', translation: 'おんな'}), pair({ word: 'комната', translation: 'へや'}),
				pair({ word: 'гора', translation: 'やま'}), pair({ word: 'машина', translation: 'くるま'})];

LESSONS[1] = [  pair({ word: 'Япония', translation: 'にほん'}), pair({ word: 'прогулка', translation: 'さんぽ'}),
				pair({ word: 'поезд', translation: 'でんしゃ'}), pair({ word: 'учебник', translation: 'きょうかしょ'}),
				pair({ word: 'школа', translation: 'がっこう'}), pair({ word: 'карандаш', translation: 'えんぴつ'}),
				pair({ word: 'огонь', translation: 'ひ'}), pair({ word: 'еда', translation: 'ごはん'}),
				pair({ word: 'дорога', translation: 'どうろ'}), pair({ word: 'обувь', translation: 'くつ'}),
				pair({ word: 'рука', translation: 'て'}), pair({ word: 'парк', translation: 'こうえん'}),
				pair({ word: 'путешествие', translation: 'りょこう'}), pair({ word: 'лес', translation: 'もり'}),
				pair({ word: 'сумка', translation: 'かばん'}), pair({ word: 'домашняя работа', translation: 'しゅくだい'}),
				pair({ word: 'время', translation: 'じかん'}), pair({ word: 'учеба', translation: 'じゅぎょう'}),
				pair({ word: 'любовь', translation: 'あい'}), pair({ word: 'вентилятор', translation: 'せんぷうき'}),
				pair({ word: 'животное', translation: 'どうぶつ'}), pair({ word: 'велосипед', translation: 'じてんしゃ'}),
				pair({ word: 'журнал', translation: 'ざっし'}), pair({ word: 'вода', translation: 'みず'})];

LESSONS[2] = [  pair({ word: 'видео', translation: 'ビデオ'}), pair({ word: 'ручка', translation: 'ペン'}),
				pair({ word: 'полотенце', translation: 'タオル'}), pair({ word: 'мяч', translation: 'ボール'}),
				pair({ word: 'бассейн', translation: 'プール'}), pair({ word: 'ложка', translation: 'スプーン'}),
				pair({ word: 'вилка', translation: 'フォーク'}), pair({ word: 'нож', translation: 'ナイフ'}),
				pair({ word: 'туалет', translation: 'トイレ'}), pair({ word: 'дверь', translation: 'ドア'}),
				pair({ word: 'штаны', translation: 'ズボン'}), pair({ word: 'костюм', translation: 'スーツ'}),
				pair({ word: 'телевизор', translation: 'テレビ'}), pair({ word: 'компьютер', translation: 'パソコン'}),
				pair({ word: 'мусор', translation: 'ゴミ'}), pair({ word: 'сумка', translation: 'バッグ'}),
				pair({ word: 'чашка', translation: 'コップ'}), pair({ word: 'сок', translation: 'ジュース'}),
				pair({ word: 'пиво', translation: 'ビール'}), pair({ word: 'ободок', translation: '力チューシャ'})];

LESSONS[3] = [	pair({ word: 'сила', translation: 'ちから'}), pair({ word: 'часы', translation: 'とけい'}),
				pair({ word: 'больница', translation: 'びょういん'}), pair({ word: 'радио', translation: 'ラジオ'}),
				pair({ word: 'математика', translation: 'すうがく'}), pair({ word: 'студент', translation: 'がくせい'}),
				pair({ word: 'университет', translation: 'だいがく'}), pair({ word: 'Россия', translation: 'ロシア'}),
				pair({ word: 'дождь', translation: 'あめ'}), pair({ word: 'снег', translation: 'ゆき'}),
				pair({ word: 'Йена', translation: 'えん'}), pair({ word: 'цветок', translation: 'はな'}),
				pair({ word: 'перерыв', translation: 'きゅうけい'}), pair({ word: 'рыба', translation: 'さかな'}),
				pair({ word: 'наличные', translation: 'げんきん'}), pair({ word: 'Луна', translation: 'つき'}),
				pair({ word: 'слово', translation: 'ことば'}), pair({ word: 'рот', translation: 'くち'}),
				pair({ word: 'страна', translation: 'くに'}), pair({ word: 'ребенок', translation: 'こども'})];

LESSONS[4] = [	pair({ word: 'зонт', translation: 'かさ'}), pair({ word: 'бумага', translation: 'かみ'}),
				pair({ word: 'ухо', translation: 'みみ'}), pair({ word: 'день рождения', translation: 'たんじょうび'}),
				pair({ word: 'отец', translation: 'ちちおや'}), pair({ word: 'мать', translation: 'ははおや'}),
				pair({ word: 'утро', translation: 'あさ'}), pair({ word: 'ночь', translation: 'よる'}),
				pair({ word: 'солнце', translation: 'たいよう'}), pair({ word: 'весна', translation: 'はる'}),
				pair({ word: 'лето', translation: 'なつ'}), pair({ word: 'осень', translation: 'あき'}),
				pair({ word: 'зима', translation: 'ふゆ'}), pair({ word: 'блюдо', translation: 'りょうり'}),
				pair({ word: 'свадьба', translation: 'けっこん'}), pair({ word: 'мясо', translation: 'にく'}),
				pair({ word: 'овощи', translation: 'やさり'}), pair({ word: 'коробка', translation: 'はこ'}),
				pair({ word: 'зеркало', translation: 'かがみ'}), pair({ word: 'земля', translation: 'つち'}),
				pair({ word: 'глаз', translation: 'め'})];

LESSONS[5] = [	pair({ word: 'пульт', translation: 'リモコン'}), pair({ word: 'игра', translation: 'ゲーム'}),
				pair({ word: 'палка', translation: 'ぼう'}), pair({ word: 'яйцо', translation: 'たまご'}),
				pair({ word: 'зубная щетка', translation: 'ハブラシ'}), pair({ word: 'ванна', translation: 'ふろ'}),
				pair({ word: 'мобильный телефон', translation: 'けいたいでんわ'}), pair({ word: 'путь', translation: 'みち'}),
				pair({ word: 'прихожая', translation: 'げんかん'}), pair({ word: 'шина', translation: 'タイヤ'}),
				pair({ word: 'пакет', translation: 'ふくろ'}), pair({ word: 'газ', translation: 'ガス'}),
				pair({ word: 'косметика', translation: 'けしょうひん'}), pair({ word: 'духи', translation: 'こうすい'}),
				pair({ word: 'фотоаппарат', translation: 'カメラ'}), pair({ word: 'здание', translation: 'たてもの'}),
				pair({ word: 'колонки', translation: 'スピーカー'}), pair({ word: 'кость', translation: 'ほね'})];

//Offline Lesson 1
LESSONS[6] = [	pair({ word: 'голубой', translation: 'あおい'}), pair({ word: 'лицо', translation: 'かお'}),
                pair({ word: 'голос', translation: 'こえ'}), pair({ word: 'дом', translation: 'いえ'}),
                pair({ word: 'воздух', translation: 'くうき'}), pair({ word: 'хризантема', translation: 'きく'}),
                pair({ word: 'красный', translation: 'あかい'}), pair({ word: 'любовь', translation: 'あい'}),
                pair({ word: 'много', translation: 'おおい'}), pair({ word: 'семья', translation: 'かぞく'}),
                pair({ word: 'вкус', translation: 'あじ'}), pair({ word: 'самочувствие', translation: 'ぐあい'}),
                pair({ word: 'наконец то', translation: 'あげく'}), pair({ word: 'продолжать', translation: 'つづく'}),
                pair({ word: 'школа', translation: 'がっこう'}), pair({ word: 'журнал', translation: 'ざっし'}),
                pair({ word: 'высокий', translation: 'たかい'}), pair({ word: 'маленький', translation: 'ちいさい'}),
                pair({ word: 'карта (географическая)', translation: 'ちず'}), pair({ word: 'университет', translation: 'だいがく'}),
                pair({ word: 'колокольчик', translation: 'すず'}), pair({ word: 'вкусный', translation: 'おいしい'}),
                pair({ word: 'тихий', translation: 'しずか'}), pair({ word: 'мелкая', translation: 'あさい'}),
                pair({ word: 'сомнение', translation: 'うたがい'}), pair({ word: 'старшая школа', translation: 'こうこう'}),
                pair({ word: 'осень', translation: 'あき'}), pair({ word: 'станция', translation: 'えき'}),
                pair({ word: 'ученик', translation: 'せいとう'}), pair({ word: 'большой', translation: 'おおきい'}),
                pair({ word: 'писать', translation: 'かく'}), pair({ word: 'аэропорт', translation: 'くうこう'}),
                pair({ word: 'ключи', translation: 'かぎ'})];
//Offline Lesson 2
LESSONS[7] = [	pair({ word: 'цифра', translation: 'すうじ'}), pair({ word: 'эпоха', translation: 'じだい'}),
                pair({ word: 'ветер', translation: 'かぜ'}), pair({ word: 'правильный ответ', translation: 'ただしい こたえ'}),
                pair({ word: '(мой) дом', translation: 'うち'}), pair({ word: 'поклон', translation: 'おじぎ'}),
                pair({ word: 'абсолютный', translation: 'ぜったい'}), pair({ word: 'прекрасный', translation: 'うつくしい'}),
                pair({ word: 'слон', translation: 'ぞう'}), pair({ word: 'красивый', translation: 'すてき'}),
                pair({ word: 'люблю', translation: 'すき'}), pair({ word: 'длинный', translation: 'ながい'}),
                pair({ word: 'дневник', translation: 'にっき'}), pair({ word: 'собака', translation: 'いぬ'}),
                pair({ word: 'кот', translation: 'ねこ'}), pair({ word: 'горло', translation: 'のど'}),
                pair({ word: 'мама', translation: 'はは'}), pair({ word: 'цветок', translation: 'はな'}),
                pair({ word: 'человек', translation: 'ひと'}), pair({ word: 'супруги', translation: 'ふうふ'}),
                pair({ word: 'одежда', translation: 'ふく'}), pair({ word: 'змея', translation: 'へび'}),
                pair({ word: 'звезда', translation: 'ほし'}), pair({ word: 'наказание', translation: 'ばつ'}),
                pair({ word: 'цена', translation: 'ぶっか'}), pair({ word: 'стена', translation: 'かべ'}),
                pair({ word: 'родители', translation: 'ふぼ'}), pair({ word: 'кислый', translation: 'すっぱい'}),
                pair({ word: 'публикация', translation: 'はっぷ'}), pair({ word: 'сильно проголодаться', translation: 'ぺこぺこ'}),
                pair({ word: 'малюсенький', translation: 'ちっぽけな'}), pair({ word: 'лето', translation: 'なつ'}),
                pair({ word: 'здесь', translation: 'ここ'}), pair({ word: 'жаркий', translation: 'あつい'})];
//Offline Lesson 3
LESSONS[8] = [	pair({ word: 'строгий', translation: 'きびしい'}), pair({ word: 'мало', translation: 'すくない'}),
                pair({ word: 'низкий', translation: 'ひくい'}), pair({ word: 'город', translation: 'まち'}),
                pair({ word: 'путь', translation: 'みち'}), pair({ word: 'холодный', translation: 'さむい'}),
                pair({ word: 'очки', translation: 'めがね'}), pair({ word: 'алые листья', translation: 'もみじ'}),
                pair({ word: 'снег', translation: 'ゆき'}), pair({ word: 'сильный', translation: 'つよい'}),
                pair({ word: 'хороший', translation: 'よい'}), pair({ word: 'роскошный', translation: 'りっぱな'}),
                pair({ word: 'светлый', translation: 'あかるい'}), pair({ word: 'чистый', translation: 'きれいな'}),
                pair({ word: 'интересный', translation: 'おもしろい'}), pair({ word: 'газета', translation: 'しんぶん'}),
                pair({ word: 'присоединяться', translation: 'かにゅう'}), pair({ word: 'подстрекательства', translation: 'かんゆう'}),
                pair({ word: 'книга', translation: 'ほん'}), pair({ word: 'весна', translation: 'はる'}),
                pair({ word: 'спокойной ночи', translation: 'おやすみなさい'})];
//Offline Minna Lesson 1-3
LESSONS[8] = [	pair({ word: 'он/она', translation: 'あのひと'}), pair({ word: 'учитель', translation: 'きょうし'}),
                pair({ word: 'служащий фирмы', translation: 'かいしゃいん'}), pair({ word: 'служащий банка', translation: 'ぎんこういん'}),
                pair({ word: 'врач', translation: 'いしゃ'}), pair({ word: 'исследователь', translation: 'けんきゅうしゃ'}),
                pair({ word: 'словарь', translation: 'じしょ'}), pair({ word: 'газета', translation: 'しんぶん'}),
                pair({ word: 'записная книжка', translation: 'てちょう'}), pair({ word: 'визитная карточка', translation: 'めいし'}),
                pair({ word: 'стол', translation: 'つくえ'}), pair({ word: 'стул', translation: 'いす'}),
                pair({ word: 'подарок', translation: 'おみやげ'}), pair({ word: 'английский язык', translation: 'えいご'}),
                pair({ word: 'прилавок, отдел', translation: 'うりば'}), pair({ word: 'подвальный этаж', translation: 'ちか'}),
                pair({ word: 'аудитория', translation: 'きょうしつ'}), pair({ word: 'столовая', translation: 'しょくどう'}),
                pair({ word: 'офис', translation: 'じむしょ'}), pair({ word: 'зал заседаний', translation: 'かいぎしつ'}),
                pair({ word: 'ресепшен', translation: 'うけつけ'}), pair({ word: 'холл', translation: 'ロビー'}),
                pair({ word: 'комната', translation: 'へや'}), pair({ word: 'туалет', translation: 'おてあらい'}),
                pair({ word: 'лестница', translation: 'かいだん'}), pair({ word: 'автомат по продаже', translation: 'じどうはんばいき'}),
                pair({ word: 'обувь', translation: 'くつ'}), pair({ word: 'дом', translation: 'うち'})];
//Offline Minna Lesson 8
LESSONS[9] = [	pair({ word: 'красивый(о мужчине)', translation: 'ハンサム'}), pair({ word: 'красивый, чистый', translation: 'きれい[な]'}),
                pair({ word: 'тихий, спокойный', translation: 'しずか[な]'}), pair({ word: 'оживленный, шумный', translation: 'にぎやか[な]'}),
                pair({ word: 'знаменитый', translation: 'ゆうめい[な]'}), pair({ word: 'добрый', translation: 'しんせつ[な]'}),
                pair({ word: 'здоровый, бодрый', translation: 'げんき[な]'}), pair({ word: 'свободный (о времени)', translation: 'ひま[な]'}),
                pair({ word: 'удобный', translation: 'べんり[な]'}), pair({ word: 'красивый, изящный', translation: 'すてき[な]'}),
                pair({ word: 'большой', translation: 'おおきい'}), pair({ word: 'маленький', translation: 'ちいさい'}),
                pair({ word: 'новый', translation: 'あたらしい'}), pair({ word: 'старый', translation: 'ふるい'}),
                pair({ word: 'хороший', translation: 'いい (よい)'}), pair({ word: 'плохой', translation: 'わるい'}),
                pair({ word: 'жаркий', translation: 'あつい'}), pair({ word: 'холодный', translation: 'さむい'}),
                pair({ word: 'прохладный', translation: 'つめたい'}), pair({ word: 'сложный', translation: 'むずかしい'}),
                pair({ word: 'легкий', translation: 'やさしい'}), pair({ word: 'высокий, дорогой', translation: 'たかい'}),
                pair({ word: 'дешевый', translation: 'やすい'}), pair({ word: 'низкий', translation: 'ひくい'}),
                pair({ word: 'интересный', translation: 'おもしろい'}), pair({ word: 'вкусный', translation: 'おいしい'}),
                pair({ word: 'занятый', translation: 'いそがしい'}), pair({ word: 'радостный', translation: 'たのしい'}),
                pair({ word: 'белый', translation: 'しろい'}), pair({ word: 'черный', translation: 'くろい'}),
                pair({ word: 'красный', translation: 'あかい'}), pair({ word: 'синий', translation: 'あおい'}),
                pair({ word: 'город', translation: 'まち'}), pair({ word: 'продукты', translation: 'たべもの'}),
                pair({ word: 'место', translation: 'ところ'}), pair({ word: 'общежитие', translation: 'りょう'}),
                pair({ word: 'ресторан', translation: 'レストラン'}), pair({ word: 'жизнь, быт', translation: 'せいかつ'}),
                pair({ word: 'работа', translation: '[お]しごと'})];
